# Generated by Django 5.1.3 on 2024-12-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_uploadedfile_status_alter_uploadedfile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="files/"),
        ),
    ]
