# Generated by Django 5.1.4 on 2025-01-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="firstname",
            field=models.CharField(default="anonymous", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="lastname",
            field=models.CharField(default="", max_length=30),
            preserve_default=False,
        ),
    ]
