# Generated by Django 5.1.4 on 2025-01-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_customuser_country_customuser_firstname_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="firstname",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="lastname",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(max_length=30),
        ),
    ]
