# Generated by Django 5.1.4 on 2025-01-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_remove_customuser_firstname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="additional_info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="rush_order",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], default="No", max_length=3
            ),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="spelling",
            field=models.CharField(
                choices=[
                    ("US", "US"),
                    ("British", "British"),
                    ("Australia", "Australia"),
                    ("Canada", "Canada"),
                ],
                default="US",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="timestamp",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], default="Yes", max_length=3
            ),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="total_cost",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="verbatim",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], default="No", max_length=3
            ),
        ),
    ]
