# Generated by Django 5.0.2 on 2026-01-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_uploadedfile_additional_info_uploadedfile_rush_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Unpaid", "Unpaid"),
                    ("Pending", "Pending"),
                    ("Paid", "Paid"),
                    ("Failed", "Failed"),
                ],
                default="Unpaid",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="paypal_payer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="paypal_payment_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
