# Generated by Django 5.0.2 on 2026-02-05 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_uploadedfile_payment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
