# Generated by Django 5.0.2 on 2026-02-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_uploadedfile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="free_trial_used",
            field=models.BooleanField(default=False),
        ),
    ]
