# Generated by Django 5.0.2 on 2026-02-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_customuser_free_trial_used"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="size",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="total_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
