# Generated by Django 5.0.2 on 2026-02-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_transcript"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="currency",
            field=models.CharField(blank=True, default="USD", max_length=10, null=True),
        ),
    ]
